<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
    /**
     * @param string $rpps
     *
     * @return array
     */
    function findPatientParMedecin($rpps)
    {

        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.medecines', 'm')
            ->where('m.rpps = :rpps')
            ->setParameter('rpps', $rpps)
        ;

        return $qb->getQuery()->getResult();
    }
}
