AppBundle\Entity\Adresse:
    type: entity
    table: adresse
    repositoryClass: AppBundle\Repository\AdresseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rue:
            type: string
            length: 255
        codePostal:
            type: integer
        ville:
            type: string
            length: '64'
    manyToOne:
        patient:
            targetEntity: AppBundle\Entity\Patient
            inversedBy: adresses
            cascade: ["persist", "remove"]
